 /******************************************************************************
 *
 * Module		: Ultrasonic Sensor
 *
 * File Name	: ultrasonic.c
 *
 * Description	: source file for the ultrasonic driver - HAL Layer
 *
 * Author		: Erini Sabry
 *
 * Date Created	: 16.10.2022
 *
 *******************************************************************************/


/*******************************************************************************
 *                                Linking Section - INCLUDES
 *******************************************************************************/
#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include "util/delay.h"

/*******************************************************************************
 *                                Global Variables
 *******************************************************************************/
static uint8 g_edgeCount = 0;
static uint16 g_timeHigh = 0;


/*******************************************************************************
 *                                Functions Definition
 *******************************************************************************/

/*******************************************************************************
 * Function Name: Ultrasonic_init
 *
 * Description :
 * 		initializes the ultrasonic sensor
 *
 * Parameters: void
 *
 * Return: void type
 *
  *******************************************************************************/
void Ultrasonic_init(void)
{
	Icu_ConfigType Icu_Config = { F_CPU_8, RISING };
	Icu_init(&Icu_Config);
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(PORTB_ID, PIN5_ID, PIN_OUTPUT);
}


/*******************************************************************************
 * Function Name: Ultrasonic_trigger
 *
 * Description :
 * 		Send the Trigger pulse to the ultrasonic.
 *
 * Parameters: void
 *
 * Return: void type
 *
  *******************************************************************************/
void Ultrasonic_trigger(void)
{
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_LOW);
}

/*******************************************************************************
 * Function Name: Ultrasonic_readDistance
 *
 * Description :
 * 		Start the measurements by the ICU from this moment.
 *
 * Parameters: void
 *
 * Return: The measured distance in Centimeter.
 *
  *******************************************************************************/
uint16 Ultrasonic_readDistance(void)
{
	Ultrasonic_trigger();
	static uint16 Ultrasonic_Distance;
	Ultrasonic_Distance = ((float32)(g_timeHigh/58.8)+2);

	return Ultrasonic_Distance;

}

/*******************************************************************************
 * Function Name: Ultrasonic_edgeProcessing
 *
 * Description :
 * 		 This is the call back function called by the ICU driver
 * 		  used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 *
 *
 * Parameters: void
 *
 * Return: void type
 *
  *******************************************************************************/
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount==1)
	{
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount==2)
	{
		g_timeHigh = Icu_getInputCaptureValue();
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(RISING);
		g_edgeCount=0;
	}
}
